import { mkdir, rm } from 'node:fs/promises';
import { $ } from 'bun';

async function build() {
  console.log('🦀 Compiling Rust to WebAssembly...');
  // Compile to standard web target
  await $`wasm-pack build --target web --out-dir ./wasm-pkg`;

  console.log('📦 Inlining Wasm & staging sources...');

  // Create a dedicated folder inside src/ to satisfy tsc's rootDir
  await rm('./src/wasm', { recursive: true, force: true });
  await mkdir('./src/wasm', { recursive: true });

  // Extract Wasm binary and write it as a Base64 TS file
  const wasmFile = Bun.file('./wasm-pkg/arkv_rng_bg.wasm');
  const wasmBuffer = await wasmFile.arrayBuffer();
  const base64Wasm =
    Buffer.from(wasmBuffer).toString('base64');

  await Bun.write(
    './src/wasm/inline.ts',
    `// Auto-generated by build.ts\nexport const WASM_BASE64 = "${base64Wasm}";\n`,
  );

  // Copy the generated bindings into src/ so tsc compiles them normally
  await Bun.write(
    './src/wasm/arkv_rng.js',
    Bun.file('./wasm-pkg/arkv_rng.js'),
  );
  await Bun.write(
    './src/wasm/arkv_rng.d.ts',
    Bun.file('./wasm-pkg/arkv_rng.d.ts'),
  );

  console.log(
    '✅ Wasm build complete and staged for TypeScript!',
  );
}

build();
